name: Scaling test for runner env ${RUNNER_ENVIRONMENT}

on:
  workflow_dispatch:
    inputs:
      numberJobs:
        description: 'Number of parallel jobs (should stay below 100)'
        required: true
        default: '${RUNNER_MAX_REPLICAS}'

jobs:
  generate-matrix:
    name: "Generate jobs for ${RUNNER_ENVIRONMENT}"
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    runs-on: [ self-hosted ]
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: echo "::set-output name=matrix::[`seq -s , ${{ github.event.inputs.numberJobs }}`]"

  stress:
    name: "Stress tests for ${RUNNER_ENVIRONMENT}"
    runs-on: [ aws, ${RUNNER_ENVIRONMENT} ]
    needs: [generate-matrix]

    strategy:
      matrix:
        job-number: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
    - name: Stress test ${{ matrix.job-number }} of env ${RUNNER_ENVIRONMENT}
      run: echo "Matrix version ${{ matrix.job-number }}" && sleep $((RANDOM%120+60))
